apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - name: wodpress
    port: 5050
    targetPort: 5050
  selector:
    app: wodpressPod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpressdeploy
spec:
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: wodpressPod
        type: wordpresstype
    spec:
      containers:
        - name: wordpresscontainer
          image: wordpress_image
          imagePullPolicy: Never
          ports:
            - name: wordpress
              containerPort: 5050
          livenessProbe:
            exec:
              command:
                - sh
                - /probe.sh
            initialDelaySeconds: 30
            periodSeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: wodpressPod
      type: wordpresstype